#!/bin/sh
# ─── Kairos Alpine Full-Disk Takeover Installer ───
# Runs INSIDE the kairos-alpine container.
# Usage: /install.sh /dev/sda <enrollment-seed-b64>
#
# The seed is a base64-encoded JSON object from the Worker:
#  { "workerUrl": "...", "token": "...", "clusterId": "...", "version": "..." }
# ──────────────────────────────────────────────────
set -e

log() { echo "[kairos-installer] $(date -Iseconds) $*"; }
die()  { log "FATAL: $*"; exit 1; }

DEVICE="$1"
SEED="$2"

[ -b "$DEVICE" ] || die "$DEVICE is not a valid block device"
[ -n "$SEED"   ] || die "enrollment seed required (base64-encoded JSON)"

# ─── Decode seed ─────────────────────────────────
log "Decoding enrollment seed..."

# Try direct decode, then with padding
echo "$SEED" | base64 -d > /tmp/enrollment.json 2>/dev/null || {
  PADDED="$SEED"
  case $(( ${#PADDED} % 4 )) in
    1) PADDED="${PADDED}===";;
    2) PADDED="${PADDED}==";;
    3) PADDED="${PADDED}=";;
  esac
  echo "$PADDED" | base64 -d > /tmp/enrollment.json 2>/dev/null || \
    die "failed to decode enrollment seed: $SEED"
}

WORKER_URL=$(jq -r .workerUrl /tmp/enrollment.json)
WORKER_TOKEN=$(jq -r .token /tmp/enrollment.json)
CLUSTER_ID=$(jq -r .clusterId /tmp/enrollment.json)
VERSION=$(jq -r .version /tmp/enrollment.json)

[ "$WORKER_URL"   != "null" ] || die "workerUrl missing from seed"
[ "$WORKER_TOKEN" != "null" ] || die "token missing from seed"

log "Worker:  $WORKER_URL"
log "Cluster: ${CLUSTER_ID:-unknown}"
log "Version: ${VERSION:-unknown}"

# ─── 1. Partition ────────────────────────────────
log "=== Partitioning $DEVICE ==="

# Detect partition suffix: NVMe and loop devices use "p" (nvme0n1p1, loop0p1)
# Regular block devices use no separator (sda1, vda1)
PART_SEP=""
case "$DEVICE" in
  /dev/nvme*|/dev/loop*) PART_SEP="p" ;;
esac

# Use sgdisk if available, fall back to gdisk
if command -v sgdisk >/dev/null 2>&1; then
  sgdisk --zap-all "$DEVICE"
  sgdisk -n 1:0:+512M -t 1:ef00 -c 1:"EFI" "$DEVICE"
  sgdisk -n 2:0:0     -t 2:8300 -c 2:"kairos-root" "$DEVICE"
elif command -v gdisk >/dev/null 2>&1; then
  gdisk "$DEVICE" <<GDISK
x
z
y
y
GDISK
  gdisk "$DEVICE" <<GDISK
n


+512M
ef00

n



8300

w
y
GDISK
else
  die "no partitioning tool found (sgdisk or gdisk required)"
fi

partprobe "$DEVICE" 2>/dev/null || true
sleep 2

EFI_PART="${DEVICE}${PART_SEP}1"
ROOT_PART="${DEVICE}${PART_SEP}2"

log "EFI:  $EFI_PART"
log "Root: $ROOT_PART"

# ─── 2. Filesystems ──────────────────────────────
log "=== Creating filesystems ==="
mkfs.vfat -F32 -n KAIROS_EFI "$EFI_PART"
mkfs.ext4 -F -L kairos-root "$ROOT_PART"

ROOT_UUID=$(blkid "$ROOT_PART" | grep -o 'UUID="[^"]*"' | cut -d'"' -f2)
log "Root UUID: $ROOT_UUID"

# ─── 3. Mount ────────────────────────────────────
log "=== Mounting target ==="
mkdir -p /mnt/target
mount "$ROOT_PART" /mnt/target
mkdir -p /mnt/target/boot
mount "$EFI_PART" /mnt/target/boot

# ─── 4. Copy rootfs ──────────────────────────────
log "=== Copying rootfs ==="
# Exclude virtual filesystems and mount points
# Note: FAT32 EFI doesn't support symlinks (e.g. /boot/boot -> .)
rsync -aAX --delete \
  --exclude='/dev' \
  --exclude='/proc' \
  --exclude='/sys' \
  --exclude='/tmp/*' \
  --exclude='/run' \
  --exclude='/mnt' \
  --exclude='/lost+found' \
  --exclude='/etc/resolv.conf' \
  --exclude='/install.sh' \
  --exclude='/var/lib/containers' \
  --exclude='/var/lib/nomad' \
  --exclude='/boot/boot' \
  / /mnt/target/ 2>&1 || log "WARNING: rsync had non-fatal errors"

mkdir -p /mnt/target/dev  /mnt/target/proc /mnt/target/sys \
         /mnt/target/tmp  /mnt/target/run  /mnt/target/mnt

cp /etc/resolv.conf /mnt/target/etc/resolv.conf 2>/dev/null || true

log "Rootfs copied ($(du -sh /mnt/target/ 2>/dev/null | cut -f1))"

# ─── 5. Install kernel (if needed) ───────────────
log "=== Installing kernel ==="

mount --bind /dev  /mnt/target/dev
mount --bind /proc /mnt/target/proc
mount --bind /sys  /mnt/target/sys

# Check if kernel exists in the copied rootfs
if ! ls /mnt/target/boot/vmlinuz-* >/dev/null 2>&1; then
  log "Kernel not in rootfs, installing via apk..."
  chroot /mnt/target apk add --no-cache linux-virt linux-firmware-none 2>&1 || \
    die "kernel install failed"
fi

KERNEL=$(ls /mnt/target/boot/vmlinuz-* 2>/dev/null | head -1 | xargs basename)
INITRD=$(ls /mnt/target/boot/initramfs-* 2>/dev/null | head -1 | xargs basename)
log "Kernel: $KERNEL"
log "Initrd: $INITRD"

# ─── 6. Enrollment seed ──────────────────────────
log "=== Writing enrollment ==="
mkdir -p /mnt/target/etc/kairos

# Env file sourced by init script
cat > /mnt/target/etc/kairos/enrollment << ENVEOF
# Generated by Kairos Installer
WORKER_URL=$WORKER_URL
WORKER_TOKEN=$WORKER_TOKEN
CLUSTER_ID=${CLUSTER_ID}
MODE=AUTO
ENVEOF

# Also write a JSON marker (for visibility)
cat > /mnt/target/etc/kairos/install-marker.json << JSONEOF
{
  "installedAt": "$(date -Iseconds)",
  "version": "${VERSION}",
  "workerUrl": "$WORKER_URL",
  "clusterId": "$CLUSTER_ID",
  "device": "$DEVICE"
}
JSONEOF

# ─── 7. Init service ─────────────────────────────
log "=== Setting up init service ==="

# Ensure entrypoint exists
[ -f /mnt/target/usr/local/bin/tinycloud-init ] || die "tinycloud-init not found in image"
chmod +x /mnt/target/usr/local/bin/tinycloud-init

cat > /mnt/target/etc/init.d/kairos-agent << 'INITSCRIPT'
#!/sbin/openrc-run
name="kairos-agent"
description="Kairos Node Agent — self-bootstrapping edge agent"

depend() {
  need net
  after bootmisc
}

start() {
  ebegin "Starting Kairos Node Agent"
  [ -f /etc/kairos/enrollment ] && . /etc/kairos/enrollment
  export WORKER_URL WORKER_TOKEN CLUSTER_ID MODE
  start-stop-daemon --start --background --make-pidfile \
    --pidfile /run/kairos-agent.pid \
    --stdout /var/log/kairos-agent.log \
    --stderr /var/log/kairos-agent.log \
    --exec /usr/local/bin/tinycloud-init -- AUTO
  eend $?
}

stop() {
  ebegin "Stopping Kairos Node Agent"
  start-stop-daemon --stop --pidfile /run/kairos-agent.pid 2>/dev/null
  eend $?
}
INITSCRIPT

chmod +x /mnt/target/etc/init.d/kairos-agent
chroot /mnt/target rc-update add kairos-agent default 2>/dev/null || {
  # Fallback: create symlink manually
  mkdir -p /mnt/target/etc/runlevels/default
  ln -s /etc/init.d/kairos-agent /mnt/target/etc/runlevels/default/kairos-agent
}

# ─── 8. Bootloader ───────────────────────────────
log "=== Installing GRUB ==="

chroot /mnt/target grub-install \
  --target=x86_64-efi \
  --efi-directory=/boot \
  --bootloader-id=kairos \
  --recheck 2>&1 || log "WARNING: grub-install failed, writing manual config"

# Manual grub.cfg as fallback / guarantee
if [ ! -f /mnt/target/boot/grub/grub.cfg ]; then
  log "Writing manual grub.cfg..."
  mkdir -p /mnt/target/boot/grub
  cat > /mnt/target/boot/grub/grub.cfg << GRUBCFG
set default=0
set timeout=5
set root=(hd0,gpt1)

menuentry "Kairos Alpine" {
  linux /$KERNEL root=UUID=$ROOT_UUID ro quiet console=ttyS0 console=tty0
  initrd /$INITRD
}

menuentry "Kairos Alpine (rescue)" {
  linux /$KERNEL root=UUID=$ROOT_UUID ro single console=ttyS0
  initrd /$INITRD
}
GRUBCFG
fi

# EFI fallback path (for firmware that ignores NVRAM)
mkdir -p /mnt/target/boot/EFI/BOOT
cp /mnt/target/boot/EFI/kairos/grubx64.efi \
   /mnt/target/boot/EFI/BOOT/BOOTX64.EFI 2>/dev/null || true

# ─── 9. Fstab ────────────────────────────────────
log "=== Writing fstab ==="
cat > /mnt/target/etc/fstab << FSTAB
# Kairos Alpine
UUID=$ROOT_UUID    /     ext4  defaults,noatime  0 1
LABEL=KAIROS_EFI   /boot vfat  defaults           0 2
tmpfs              /tmp  tmpfs defaults,noatime   0 0
FSTAB

# ─── 10. Network (ensure DHCP on boot) ───────────
# Alpine default: dhcp on eth0, but be explicit
mkdir -p /mnt/target/etc/network
cat > /mnt/target/etc/network/interfaces << IFACES
auto lo
iface lo inet loopback

auto eth0
iface eth0 inet dhcp
IFACES

# ─── 11. Cleanup ─────────────────────────────────
log "=== Cleanup ==="
umount /mnt/target/sys  2>/dev/null || true
umount /mnt/target/proc 2>/dev/null || true
umount /mnt/target/dev  2>/dev/null || true
umount /mnt/target/boot 2>/dev/null || true
umount /mnt/target      2>/dev/null || true

log ""
log "╔══════════════════════════════════════╗"
log "║  Kairos Alpine Installation Complete ║"
log "╚══════════════════════════════════════╝"
log ""
log "Device:   $DEVICE"
log "Worker:   $WORKER_URL"
log "Cluster:  ${CLUSTER_ID:-unknown}"
log "Version:  ${VERSION:-unknown}"
log ""
log "Remove rescue media and reboot."
log "First boot: ~30s to auto-enroll and join cluster."
log "Monitor:   journalctl -u kairos-agent -f"
